"""Add thumbnail uri

Revision ID: 1849bb6b7e57
Revises: 3ce3da92f858
Create Date: 2022-03-16 13:32:43.197168

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1849bb6b7e57'
down_revision = '3ce3da92f858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('thumbnail_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'thumbnail_uri')
    # ### end Alembic commands ###
