"""uploaded_at

Revision ID: 39c1fdf365c0
Revises: 55632ac588ff
Create Date: 2022-03-21 17:29:05.685464

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39c1fdf365c0'
down_revision = '55632ac588ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'uploaded', server_default=None, new_column_name='uploaded_at')
    op.drop_constraint('videolikelink_user_id_key', 'videolikelink', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'uploaded_at', server_default=None, new_column_name='uploaded')
    op.create_unique_constraint('videolikelink_user_id_key', 'videolikelink', ['user_id'])
    # ### end Alembic commands ###
