"""likes

Revision ID: 55632ac588ff
Revises: 1849bb6b7e57
Create Date: 2022-03-19 21:38:10.317951

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '55632ac588ff'
down_revision = '1849bb6b7e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videolikelink',
    sa.Column('video_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_path'], ['video.path'], ),
    sa.PrimaryKeyConstraint('video_path', 'user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('user', sa.Column('thumbnail_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'thumbnail_uri')
    op.drop_table('videolikelink')
    # ### end Alembic commands ###
