"""api-key

Revision ID: bb761dee7bcd
Revises: 39c1fdf365c0
Create Date: 2022-04-26 22:28:19.688767

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'bb761dee7bcd'
down_revision = '39c1fdf365c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_key', sa.LargeBinary(), nullable=True))
    op.add_column('user', sa.Column('salt', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salt')
    op.drop_column('user', 'api_key')
    # ### end Alembic commands ###
